name: Update Download Info

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:  # allow manual trigger
  repository_dispatch:
    types: [release-event]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Download Info and changelog.html
        run: |
          python scripts/update_release_and_changelog.py

      - name: Commit download info
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/"
          committer_name: GitHub Actions
          committer_email: actions@github.com
